title: Microclimate
email: tiaoyuw@ca.ibm.com
description: IBM Microclimate - Helping developers build services for IBM Cloud Private
keywords: IBM, microclimate, docker, container, devops, applications, development, iteration, microservices, cloud, ICP, services, rapid, integrated
baseurl: "/"
twitter_username: jekyllrb
github_username:  jekyll

# Please change both downloadlink and version for every new release.
downloadlink: download/microclimate-19.05.zip
version: "19.05"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: [node_modules]
collections:
  documentations:
    output: true
  news:
    output: true
  newsarchive:
    output: true
